### ISSUE TITLE
Possible documentation changes relating to 1.7

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3513]
I've noticed that when installing django CMS on Django 1.7/Python 2.7, from scratch, I am only successful if I:

1. Install bare Django project.
2. manage.py migrate
3. Install CMS and related as per the docs *sans* Reversion
4. manage.py migrate
5. Add 'reversion' to INSTALLED_APPS
6. manage.py migrate

I kept getting the following, if I attempted to just create the whole project, with all my configuration for CMS, then try to migrate all at once:

````
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUser'>, <ModelState: 'cms.PageUserGroup'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
````

Can anyone verify that this is a truism and if, so, I'll happily update the installation guide.

**Comment by yakky** [comment]
Fixed in #3741

**Comment by SalahAdDin** [comment]
Yes, this works for me :D Thank you.

**Comment by kakulukia** [comment]
even tho i have the migration modules set i still get this error, but only when i try to create a test database .. makemigrations and migrate commands work

what could cause this?

here is my traceback:

Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/test/runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/test/runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/test/runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/db/backends/creation.py", line 377, in create_test_db
    test_flush=True,
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/Users/andygrabow/.virtualenvs/backend/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUserGroup'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

**Comment by davydany** [comment]
@yakky, This is happening because ```MIGRATION_MODULES``` doesn't have proper migrations directory for 'cms' and 'menus'. I have the latest version on PyPI and I encountered issues, and the following has fixed the issue. I'll provide the explanation below the settings.

```python
MIGRATION_MODULES = {
    'cms': 'cms.migrations', # CHANGED HERE (look below)
    'menus': 'menus.migrations', # CHANGED HERE (look below)

    # Add also the following modules if you're using these plugins:
    'djangocms_file': 'djangocms_file.migrations_django',
    'djangocms_flash': 'djangocms_flash.migrations_django',
    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
    'djangocms_inherit': 'djangocms_inherit.migrations_django',
    'djangocms_link': 'djangocms_link.migrations_django',
    'djangocms_picture': 'djangocms_picture.migrations_django',
    'djangocms_snippet': 'djangocms_snippet.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django',
    'djangocms_video': 'djangocms_video.migrations_django',
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_column': 'djangocms_column.migrations_django',

}
``` 

Instead of 
```python
MIGRATION_MODULES = {
    'cms': 'cms. migrations_django',
    'menus': 'menus. migrations_django',

    # Add also the following modules if you're using these plugins:
    'djangocms_file': 'djangocms_file.migrations_django',
    'djangocms_flash': 'djangocms_flash.migrations_django',
    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
    'djangocms_inherit': 'djangocms_inherit.migrations_django',
    'djangocms_link': 'djangocms_link.migrations_django',
    'djangocms_picture': 'djangocms_picture.migrations_django',
    'djangocms_snippet': 'djangocms_snippet.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django',
    'djangocms_video': 'djangocms_video.migrations_django',
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_column': 'djangocms_column.migrations_django',

}
```

The reason why is because DjangoCMS's ```cms``` and ```menus``` package don't have a directory named ```migrations_django``` in their application directory. Instead, they have a folder called ```migrations```, and setting MIGRATION_MODULES to point to that folder in each application fixes it.

**CMS App:** https://github.com/divio/django-cms/tree/develop/cms/migrations
**Menus App:** https://github.com/divio/django-cms/tree/develop/menus/migrations

**Comment by yakky** [comment]
django CMS 3.1 has the new (proper) layout which does not require any setting in ``MIGRATION_MODULES`` as documented in upgrade guide and documentation
