### ISSUE TITLE
Missing migration with Django 1.7 (DjangoCMS 3.0.6)

### ISSUE THREAD

**Issue by shatsinn** [divio/django-cms#3572]
Starting a project with Django 1.7 and DjangoCMS 3.0.6 will result in Django's `makemigrations` creating another migration file for the `cms` app. You can see the the created migration file here:

http://paste.awesom.eu/ZnyI

This gets annoying when creating custom plugins which then automatically depend on the locally created 0004 `cms` migration: It breaks deployment on a remote machine. My current fix is to manually edit the custom plugins' migration files to depend on the shipped 0003 `cms` migration.

I noticed that Django's migration system is more sensitive to changes than South, so could you please run `makemigrations` on all your cms apps (noticed a similar issue with `djangocms_link`) before the next release? Thanks!

**Comment by Hamms** [comment]
I am also encountering this issue with Django 1.7 and Django-cms 3.0.9

**Comment by yakky** [comment]
What's the resulting code of the migration?

**Comment by Hamms** [comment]
```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsplugin',
            name='plugin_type',
            field=models.CharField(verbose_name='plugin_name', max_length=50, editable=False, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='title',
            name='has_url_overwrite',
            field=models.BooleanField(default=False, verbose_name='has url overwrite', db_index=True, editable=False),
            preserve_default=True,
        ),
    ]
```

**Comment by yakky** [comment]
Tried on a fresh project started with nephila/djangocms-installer and can't reproduce this on 3.0.10.
Django 1.7 is quite sensitive and errs on the safe side generating migration with no real changes.
Possibly some third-party application that for some reason triggers django db migration into thinking a database schema change has occurred

**Comment by Hamms** [comment]
The project I'm encountering this on was also created with djangocms-installer, and so far is quite simple. I believe I first encountered this error upon adding my first custom CMS plugin.

I updated my cms version to 3.0.10 and am still experiencing the error.

**Comment by tomassommar** [comment]
I'm experiencing the same issue on djangocms 3.0.10 running on django 1.7.4, but originating from the djangocms_blog plugin. 
```
KeyError: u"Migration djangocms_blog.0001_initial dependencies reference nonexistent parent node (u'cms', u'0003_auto_20140926_2347')"
```

**Comment by Hamms** [comment]
That is a different, albeit similar, problem.

**Comment by Hamms** [comment]
Is there any opposition to simply adding the `0004_auto` migration to the project?

**Comment by yakky** [comment]
I'm definitely not keen adding a migration which can't be reproduced on stock django CMS project: we need to fix the issue that triggers the new (unneeded) migration, instead

**Comment by jsma** [comment]
The verbose names were changed in the migrations so they are out of sync with the models. That is why there are spurious migrations. I have a fix coming in the next few seconds but read on for background.

In 3.0.10, the 0002 migration has `verbose_name='has URL overwrite'` which was changed in https://github.com/divio/django-cms/commit/89a95b7393119fdeecff9c16f9757482fdf46e00 but the model's verbose_name is 'has url overwrite' (all lower case).

https://github.com/divio/django-cms/commit/3ffd7e6e60ab2d2ac69431c70a8d4db45ede0b69 changed the verbose name for CMSPlugin.plugin_type field from 'plugin_name' to 'plugin name'.

**Comment by yakky** [comment]
@jsma thanks! I must be 1.7 migration blind: I think I checked three or four times the fields attribute without spotting the difference.

**Comment by jsma** [comment]
I've been bitten by this type of issue before, so a little extra sensitive to it ;) In fact, just had to fix some migrations on another project minutes ago.

**Comment by yakky** [comment]
Fixed by #3916

**Comment by shatsinn** [comment]
Sorry, but it's still broken. I just tried a fresh install:

```
$ virtualenv --python=python2.7 cmstest
$ cd cmstest/
$ . bin/activate
$ pip install djangocms-installer
$ djangocms --parent-dir cmstest cmstest  # leave defaults except 3.0 for CMS and 1.7 for Django, en for language
$ cd cmstest
$ ./manage.py migrate  # should tell me nothing has changed, but:

Your models have changes that are not yet reflected in a migration, and so
won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run
  'manage.py migrate' to apply them.


$ ./manage.py makemigrations

Migrations for 'cms':
  0004_auto_20150307_0249.py:
      - Alter field plugin_type on cmsplugin
      - Alter field has_url_overwrite on title

$ cat ../lib/python2.7/site-packages/cms/migrations_django/0004_auto_20150307_0249.py 

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsplugin',
            name='plugin_type',
            field=models.CharField(verbose_name='plugin name', max_length=50, editable=False, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='title',
            name='has_url_overwrite',
            field=models.BooleanField(default=False, verbose_name='has URL overwrite', db_index=True, editable=False),
            preserve_default=True,
        ),
    ]

$ pip freeze
dj-database-url==0.3.0
Django==1.7.5
django-classy-tags==0.6.1
django-cms==3.0.12
django-mptt==0.6.1
django-reversion==1.8.5
django-sekizai==0.8.1
djangocms-admin-style==0.2.5
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.1
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.2
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
html5lib==0.999
Pillow==2.7.0
pytz==2014.10
requests==2.5.3
six==1.9.0
South==1.0.2
```

Python is 2.7.9

**Comment by shatsinn** [comment]
I wonder where the migrations gets 'has URL overwrite' from. Grep can only find it in the english translation (and the newly created migration file):

```
$ grep -r 'has URL overwrite' ../lib/python2.7/site-packages/cms/*
Übereinstimmungen in Binärdatei ../lib/python2.7/site-packages/cms/locale/en/LC_MESSAGES/django.mo.
../lib/python2.7/site-packages/cms/locale/en/LC_MESSAGES/django.po:msgstr "has URL overwrite"
../lib/python2.7/site-packages/cms/migrations_django/0004_auto_20150307_0249.py:            field=models.BooleanField(default=False, verbose_name='has URL overwrite', db_index=True, editable=False),
```

**Comment by lucaippo** [comment]
For what it's worth, I can confirm the issue still persists with version 3.0.12
Link to mailing list discussion: https://groups.google.com/forum/#!topic/django-cms/OYjlmOAHGeE

**Comment by timgraham** [comment]
I think the root cause is that the English translation [doesn't match doesn't match the string used in the model](https://github.com/divio/django-cms/blob/ce075ff5c690e1f47cb17268d5ad3aa8a768a971/cms/locale/en/LC_MESSAGES/django.po#L933-L935).
```
#: models/titlemodels.py:25
msgid "has url overwrite"
msgstr "has URL overwrite"
```
`makemigrations` forces the locale to `en-us` in order to generate migrations that are consistent regardless of `settings.LANGUAGE_CODE`.

**Comment by jsma** [comment]
Ah, I couldn't reproduce this in my own test project project because I had `USE_I18N = False`. I think it's just doing a no-op on `_()` calls when fetching verbose_name strings and `USE_I18N = False` so the translation string didn't enter into the equation in my setup. At any rate, attempting to get some answers on IRC so I can get the translation strings fixed. Thanks everyone for the report and your patience/persistence.

**Comment by shatsinn** [comment]
Do you want me to open a new issue or will this be reopened? :)

**Comment by marksweb** [comment]
I've just come across the same problem here.

We've setup two new projects recently, yesterday I had to fix an issue with a missing CMS migration on a project setup by a colleague and now I'm setting up my own new project.

Django 1.7.6, cms 3.0.12.

If I run `makemigrations` I get;

```bash
Migrations for 'cms':
  0004_auto_20150317_1039.py:
    - Alter field plugin_type on cmsplugin
    - Alter field has_url_overwrite on title
```

And again, the issue I fixed yesterday with a migration dependency was from CMS on a 0004 migration.

**Comment by yakky** [comment]
@marksweb 3.0.13 will solve this

**Comment by leonsmith** [comment]
I can't find any indication that there will be a 3.0.13 release so I'm presuming this fix has been rolled into 3.1?

Is there any possibility of getting a final 3.0.13 release? we have a few sites between 3.06 - 3.0.12 versions and running the upgrade path for 3.0X to 3.1 seems a little step to get a fix for this bug?

**Comment by yakky** [comment]
@leonsmith 3.0.13 will be issued shortly
