### ISSUE TITLE
Delete page shouldn't result in 404

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3654]
Currently when you delete a page, the user is redirected to the url of the page that was just deleted. It should instead redirect to the parent page, if one exists or to the home page rather than giving the user an error page.

**Comment by jedie** [comment]
:+1: run into the same problem.

(Fix is https://github.com/divio/django-cms/pull/3894 isn't it?)

**Comment by yakky** [comment]
@jedie yes
It will be forward ported by merging 3.0.x into develop

**Comment by yakky** [comment]
@jsma @jedie  could you please test #3894?

**Comment by jsma** [comment]
This appears to still be a problem on develop. Maybe there is more work required beyond applying this PR but it seems that the page is already deleted, so when it attempts `obj = ctype.get_object_for_this_type(pk=pk)` it doesn't exist and returns the empty string as the redirect url (so it just reloads the url for the deleted page, 404-ing).

**Comment by jedie** [comment]
Think this also happens if you rename a page, too. IMHO i see this with 3.0.12 but i must test it again...

**Comment by mkoistinen** [comment]
Fixed by #3894

**Comment by jsma** [comment]
@mkoistinen see my [previous comment](https://github.com/divio/django-cms/issues/3654#issuecomment-87483086), this is not fixed in 3.1.0rc1. Please re-open.

**Comment by yakky** [comment]
@jsma fix was broken again in some way. I think this is not going to be fixed in 3.1, but of will in the next patch release

**Comment by jsma** [comment]
Lost track of this. Just tested on develop, it appears to only refresh the side-frame for page administration but leaves the actual page untouched. This is an improvement since it doesn't immediately result in an error for the user, but if they reload the current page manually, then they'll get the 404. Was there a decision made on whether to redirect and where to redirect?

**Comment by yakky** [comment]
@jsma could you test latest 3.0.x branch? Latest fix has been merged there and will be forward ported after 3.0.15 release

**Comment by yakky** [comment]
@jsma fix has been ported to support/3.1.x

**Comment by yakky** [comment]
Fixed by #4229
