### ISSUE TITLE
Proposal: Added PageField to Title for redirects

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3678]
Currently only a hardcoded slug or full url is allowed for setting a page redirect. It would be far more flexible for internal redirects to have the option of linking to other published Page instances.

**Comment by yakky** [comment]
This has been fixed in 3.0.9 (#3712) / develop
The page still has a link to an hardcoded URL, but the UI allows to select the proper page instead of handwriting it

**Comment by jsma** [comment]
That doesn't quite solve what I was aiming for in this ticket. I was envisioning something like the link plugin where you can enter a fully qualified url (for external links) or relative path (for urls handled by a Django app, e.g. /login/ etc., not a CMS page) OR you could use the page select widget to FK to an actual Page. This can be very handy in development when the slugs might change frequently when the page urls are tuned from the defaults for SEO prior to launch (there can be many rounds of edits).

**Comment by jsma** [comment]
Hit 'comment' too soon. If the feature I proposed is agreeable, please reopen the ticket and I'll try to get a pull request put together soon.
