### ISSUE TITLE
Broken undo causes corruption in page. Kills page view and page publish operations.

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#3811]
An undo error 'Could not revert revision, due to database integrity errors.' caused Page field 'publisher_public' to become unhinged. It's a double link between draft and live version, but if one of those links is broken (not both!) then the page is in an unstable state.

We had publisher_public==None in the draft(pk=2) and publisher_public==2 set in the live version(pk=942). This meant viewing the page threw error A and attempting to publish the page threw error B.

A:
```
File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/models/pagemodel.py", line 954, in has_view_permission
    return self.publisher_draft.has_view_permission(request, user)
DoesNotExist: Page has no publisher_draft.
```

B:
```
File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/models/pagemodel.py", line 574, in publish
    public_page.save()
IntegrityError: (1062, "Duplicate entry '2' for key 'publisher_public_id'")
```

The error had to be fixed manually from a django shell:
```
Page.objects.filter(pk=2).update(publisher_public=Page.objects.filter(publisher_public=2)[0])
```
But idealy the software would be able to detect these issues and repair itself, especially when hitting the publish button.

**Comment by steffenmllr** [comment]
I ran into the same issue. Any idea what's causing this and how I can prevent this from happening?

**Comment by yakky** [comment]
Could you please check if this is solved in 3.0.10?

**Comment by jproffitt** [comment]
I hit this issue with 3.1.0, and reversion 1.8.7

**Comment by kelvan** [comment]
Just ran into this in 3.1.1
Deleted picture (not the ImagePlugin)
Plugin gone from page
Undo -> 500
Page broken

**Comment by yakky** [comment]
@kelvan A filer plugin?

**Comment by kelvan** [comment]
yes, was an filer_image

**Comment by yakky** [comment]
@doctormo @kelvan @jproffitt could you test https://github.com/divio/django-cms/pull/4235
It's still WiP and a bit rough, but should already solve the issue

**Comment by yakky** [comment]
@doctormo @kelvan @jproffitt the best option we have to fix this is #4235, which works on sqlite and postgres and not on mysql

**Comment by creimers** [comment]
@yakky You're asking if it was  a filer plugin. We have a customer reporting that he lost an instance of some model upon changing a FilerImageField attribute. Have you heard of this before by chance?

I have not been able to reproduce the behavior so I can not say if it indeed occurred the way described by the customer. It might as well be that they did something wrong.

**Comment by yakky** [comment]
@creimers honestly I don't remember why I asked if it  was a filer plugin :)
anyway, this could be possibly fixed in next 3.2 version when using reversion 1.10 which uses transactions natively (imply using Django 1.7+, though)

**Comment by creimers** [comment]
@yakky This problem persists for me in a djangocms 3.2 project. The customer changes a filer image in a custom plugin, upon which the whole plugin 'disappears' . Trying to use 'undo' results in `Page has no publisher_draft`. 

If I access the concerning Page model via `manage.py shell` and restore the publisher draft, the plugin on the page indeed claims to be empty (German: 'Leer'):

<img width="488" alt="bildschirmfoto 2016-01-19 um 12 58 13" src="https://cloud.githubusercontent.com/assets/6090492/12417990/767bcf6e-beac-11e5-8e14-7e369c975b77.png">

I'm still trying to reproduce this behavior, but I'm pretty sure it's not a layer 8 problem on the client side.

Any thoughts by chance?

**Comment by yakky** [comment]
@creimers reversion 1.10 natively implements transaction support.
reversion 1.10 support should be released in next 3.2 patch version (current release/3.2 already implements the basic 1.10 support, but some fixes are still in the work)
Alternatively you can check https://github.com/divio/django-cms/pull/4235 which is not going to be merged because of issues with mysql

**Comment by creimers** [comment]
@yakky Sorry, it was a layer 8 problem after all. The customer was deleting a filer image that was still used by other plugins and the respective fields did not have 'on_delete = models.SET_NULL'...

**Comment by mkoistinen** [comment]
@creimers Can you test this with the latest release in the repo at release/3.2.x with latest Reversion and possibly even Django 1.9? We believe this should prevent this sort of thing.

**Comment by yakky** [comment]
Fixed (hopefully) in 3.2.1

**Comment by yunmanger1** [comment]
Just ran into this. Here is a screenshot from sentry

![screencapture-app-getsentry-com-sdu-sdu-website-issues-117293552-1458130173886](https://cloud.githubusercontent.com/assets/388285/13811860/a948b998-eba2-11e5-9234-c8d9667ef1e3.png)

**Comment by takeontom** [comment]
Hi,

Just hit this issue in DjangoCMS 3.2.3.

What info can I give to help?

**Comment by FinalAngel** [comment]
@yakky we also ran into those issues recently, one of the problem is, that the history affects all languages at once and not separately. Here the extract on our internal findings:.

```
When publishing a page for the first time, the CMS will create another "page" object and link it to the page object being published, resulting in a draft and live page.

This procedure also happens for the title objects attached to a page, whenever a page is first published,
the CMS will create a "live" title for each "draft" one.

One of the issues: page x "draft" page lost the reference to it's "live" page, also all the titles lost the reference to their "live" version. So whenever an admin would try to publish a page after this, the CMS would throw an unhandled exception because the pages were in an inconsistent state (corrupt).

Observations:

- Multiple edits by two users on the same page within the same minute
- Revisions are broken and quite inefficient as they will override all languages inside the page.
- Publishing/restoring will delete several versions, thus making it impossible to traceback steps (sad)
- Seems to me (paulo) this issue only happens to parent pages, meaning that it's somehow linked to subpages.
```

**Comment by yakky** [comment]
@FinalAngel would you rather reopen this or open a new issue to track the problems after the fix for this has been applied?

**Comment by FinalAngel** [comment]
I'd be for reopen @yakky

**Comment by czpython** [comment]
Closing as we're refactoring reversion integration.

**Comment by akx** [comment]
Just signaling that @doctormo 's fix in the first post rescued a production site for us (`django-cms==3.3.1`) :)
