### ISSUE TITLE
Placeholder in plugin

### ISSUE THREAD

**Issue by antofik** [divio/django-cms#4206]
Though it is possible to place placeholder inside plugin, when you'll try to place there any content, you not find it in edit mode. It is just not displayed.

The problem is, in edit-mode, all $(".cms-plugins") are set dispaly=none. But code, that calculates relative positions of placeholders (cms.structureboad.js => _resizeBoard) uses $("placeholder").offset() function, which will return (0,0) for such placeholders, since they are hidden.

It is very pity, since using placeholdres in plugins is very common scenario. 
Let me show one quite common. You have plugin "news". Which is just simple list of news. But somewhere among news there could be items "banners", like this:

News
  - news
  - news
  - banner
  - news
  - news

Understandable, that one would like to put {% placeholder "banner" %} on the place of banner

Best regards

**Comment by antofik** [comment]
Bearing in mind, that there will be plugins inside plugins, I would think, that much easier and convenient would be to show all placeholders in simple list, without trying to position them on the page.
Moreover, positioning will fail if placeholder is shown only on when condition met (say, we have overlay with "special offer", which is shown only for some visitors, and we want to mange it via placeholders

**Comment by antofik** [comment]
I could provide PR, if needed

**Comment by yakky** [comment]
I am not a fan of placeholders in plugins. @mkoistinen @FinalAngel, any opinion?

**Comment by antofik** [comment]
Placeholders in plugins is just more general form of "plugins in plugins", which is supported feature.
But with current scheme of "plugins in plugins" one could place children plugins in parent template only as list. Or create some hacks, like this one: create wrapper with model:

```
class Model:
    TYPES = (('left_banner', 'left_banner'), 
                    ('right_banner', 'right_banner'), 
                    ('auth_control', 'auth_control'),  
                    ('comment_form', 'comment_form'))
    type = models.CharField(choices=TYPES)
```

And then place each child plugin according to its type. But this looks a bit ugly, Especially since system already supports placeholderes in plugins. All we need is front-end support :)

**Comment by FinalAngel** [comment]
wouldn't this be automatically solved with: https://github.com/divio/django-cms/pull/4185 as the placeholder are not absolute positioned anymore?

@antofik can you try if that works for you?

**Comment by antofik** [comment]
Sorry for delay, for some reason I haven't received email notification
Unfortunately, it does not solve the problem. Please, have a look at screenshot 
![django-cms-bug](https://cloud.githubusercontent.com/assets/2310260/9078791/dfdc4878-3af7-11e5-8eb4-8e40218bc0c2.jpg)

**Comment by FinalAngel** [comment]
awesome, closing than :)
