### ISSUE TITLE
RemovedInDjango19Warnings

### ISSUE THREAD

**Issue by blueyed** [divio/django-cms#4243]
With Django 1.8 there are several `RemovedInDjango19Warning` warnings triggered by django-cms:

> RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.

via:

    cms/admin/placeholderadmin.py
    8:from django.contrib.admin.util import get_deleted_objects

    cms/admin/pageadmin.py
    15:from django.contrib.admin.util import get_deleted_objects

    cms/tests/permmod.py
    6:from django.contrib.admin.util import unquote

And `django.utils.importlib will be removed in Django 1.9.` via:

      …/django-cms/cms/utils/django_load.py(15)<module>()
         13 import traceback # changed
         14 
    ---> 15 from django.utils.importlib import import_module
         16 from django.utils.six.moves import filter, map
         17

**Comment by yakky** [comment]
@blueyed which django CMS version are you using? With django CMS 3.1.2 there should be no warning regarding 1.9

**Comment by blueyed** [comment]
@yakky
I was using the develop branch, but it's the same with 3.1.2.

`cms/utils/django_load.py` is using `from django.utils.importlib import import_module`, for example.

**Comment by yakky** [comment]
@blueyed #4255 should remove any deprecation warning in the django CMS codebase.
Thanks for sharing this

**Comment by yakky** [comment]
Fixed in #4255

**Comment by jproffitt** [comment]
I'm still seeing a couple of `RemovedInDjango19Warning`'s after upgrading to CMS 3.1.3:

    cms/models/permissionmodels.py:7: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

    cms/utils/compat/forms.py:11: RemovedInDjango19Warning: django.db.models.get_app is deprecated.
