### ISSUE TITLE
Install Error: AttributeError: 'NoneType' object has no attribute '_meta'

### ISSUE THREAD

**Issue by sepi2048** [divio/django-cms#4275]
I am trying to install djangoCMS on my Ubuntu 15.04. 
I installed django CMS inside the virtualenv like this:

`pip install djangocms-installer`

First I had a "pillow not compiled with jpeg" issue, but managed to solve it by installing another pip version (pip install Pillow==2.3) before running `djangocms -f -p . myproject.`

**Now, I keep getting the following error:**
`
Running migrations:
      Rendering model states...Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 104, in migrate
        state = migration.mutate_state(state, preserve=do_run)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 83, in mutate_state
        operation.state_forwards(self.app_label, new_state)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 53, in state_forwards
        list(self.managers),
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 81, in add_model
        self.reload_model(app_label, model_name)
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 122, in reload_model
        related_models.update(get_related_models_recursive(rel_model))
      File "/home/user/.virtualenvs/folder/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 57, in get_related_models_recursive
        rel_app_label, rel_model_name = rel_mod._meta.app_label, rel_mod._meta.model_name
    AttributeError: 'NoneType' object has no attribute '_meta' `

**Here is my pip freeze:**
`
cmsplugin-filer==0.10.1
dj-database-url==0.3.0
Django==1.8.3
django-appconf==1.0.1
django-classy-tags==0.6.2
django-cms==3.1.2
django-filer==0.9.11
django-mptt==0.7.4
django-polymorphic==0.7.1
django-reversion==1.8.5
django-sekizai==0.8.2
Django-Select2==4.3.1
django-treebeard==3.0
djangocms-admin-style==0.2.7
djangocms-column==1.5
djangocms-flash==0.2.0
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.8
djangocms-link==1.6.2
djangocms-style==1.5
djangocms-text-ckeditor==2.5.2
easy-thumbnails==2.2
html5lib==0.999999
Pillow==2.3.0
pytz==2015.4
six==1.9.0
tzlocal==1.2
Unidecode==0.4.18
wheel==0.24.0
`

**Comment by yakky** [comment]
This is apparently related to some issues in reversion / cmsplugin-filer / GenericForeignKeys

**Comment by yakky** [comment]
This actually is a filer issue see stefanfoulis/django-filer#523

**Comment by yakky** [comment]
Patch available at stefanfoulis/django-filer#559

**Comment by yakky** [comment]
Fixed in filer

**Comment by boydjohnson** [comment]
This issue is not fixed yet. We are seeing `AttributeError: 'NoneType' object has no attribute '_meta'` when using `cms.models.fields.PageField` in any custom plugin models in our current set of migrations when we tried to upgrade from Django 1.7.x to 1.8.x. The problem also exists in the cms code base itself not just django-filer.

We have fixed the issue by using the same fix / technique that was used in stefanfoulis/django-filer#559.

Changed `cms.models.fields.PageField` to include:

```
def get_model_label(model):
    """
    Take a model class or model label and return its model label.
    >>> get_model_label(MyModel)
    "myapp.MyModel"
    >>> get_model_label("myapp.MyModel")
    "myapp.MyModel"
    """
    if isinstance(model, six.string_types):
        return model
    else:
        return "%s.%s" % (
            model._meta.app_label,
            model.__name__
        )
```
And then updated `PageField`'s __init__ def to be:

```
    def __init__(self, **kwargs):               
        # We hard-code the `to` argument for ForeignKey.__init__
        # since a PageField can only be a ForeignKey to a Page
        dfl = get_model_label(self.default_model_class)
        if "to" in kwargs.keys():  # pragma: no cover
            old_to = get_model_label(kwargs.pop("to"))
            if old_to != dfl:
                msg = "%s can only be a ForeignKey to %s; %s passed" % (
                    self.__class__.__name__, dfl, old_to
                )
                warnings.warn(msg, SyntaxWarning)
        kwargs['to'] = dfl
        super(PageField, self).__init__(**kwargs) 
```

Would you like us to do a PR for this?  If yes, please let me know where in the `utils` you would like `get_model_label` to live.

**Comment by yakky** [comment]
@boydjohnson this should have been fixed in current support/3.1 branch with 40607f6d09527665c8f5dd8c9be31b0f711608a1

**Comment by boydjohnson** [comment]
@yakky Do you have a release date in mind?

**Comment by yakky** [comment]
@boydjohnson mid august, as soon as I'm back from holiday :smile:
