### ISSUE TITLE
Getting a JS error when using custom change_form in plugins.

### ISSUE THREAD

**Issue by philippeowagner** [divio/django-cms#4334]
Getting ``Uncaught Error: Syntax error, unrecognized expression: #id_page_link_2 option[value=]`` on this [``$("#id_%(name)s_2 option[value=]")``](https://github.com/divio/django-cms/blob/59761231b7053ab1bbb9c6a3e860a39cd1f54621/cms/forms/widgets.py#L107) when using a custom change_form for a plugin. We have another select2 in there. 
Adding a ``try,catch`` around it worked for us - even omitting the ``else`` branch...  Will create a PR in case it's confirmed by others.

**Comment by evildmp** [comment]
@FinalAngel Would you be able to review issue and patch please?

**Comment by FinalAngel** [comment]
I'll keep it on my radar @evildmp

**Comment by yakky** [comment]
Fixed in #4486

**Comment by philippeowagner** [comment]
Thanks!

**Comment by jproffitt** [comment]
I don't think the patch fixes it. Using this patch, I still get the error:

    [Error] Error: Syntax error, unrecognized expression: #id_contact_page_2 option[value=]

I just have a simple model with a `PageField`. If the jQuery is trying to get all options under the select that  have a value, I think it should be `$("#id_%(name)s_2 option[value]").attr('selected', true);` (note the MISSING `=`)

See the jQuery docs: https://api.jquery.com/has-attribute-selector/

**Comment by yakky** [comment]
@jproffitt #4546 should. It will be forward ported to 3.1 in the next days
