### ISSUE TITLE
`on_close` parameter on CMSToolbar.add_modal_item doesn't do anything

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#4344]
If a URL is supplied, it should redirect to given URL on close.

**Comment by yakky** [comment]
@mkoistinen have you tested on latest support? This should have been fixed by #4229

**Comment by mkoistinen** [comment]
Can this be forward-ported to 3.1.x?

**Comment by mkoistinen** [comment]
I've tested this with latest develop and the issue persists.

**Comment by yakky** [comment]
@mkoistinen do we need this in 3.0.15 or we can postpone it?

**Comment by mkoistinen** [comment]
I marked it blocker, but it doesn't have to be.

**Comment by vxsx** [comment]
I think we fixed this in 3.2 preview.

**Comment by vxsx** [comment]
Should've been fixed as part of https://github.com/divio/django-cms/pull/4473 and subsequent change in https://github.com/divio/django-cms/pull/4478

**Comment by vxsx** [comment]
I was wrong

**Comment by yakky** [comment]
@vxsx could you backport the fix to 3.0/3.1 ?

**Comment by yakky** [comment]
@vxsx @FinalAngel any update on this?

**Comment by vxsx** [comment]
@yakky sadly no, had been quite busy with 3.2, but this one is still on my radar

**Comment by yakky** [comment]
@vxsx thanks

**Comment by FinalAngel** [comment]
@qnub we fixed the on_close behaviour for modal and sideframe?

**Comment by czpython** [comment]
@vxsx any updates on this? is it still relevant?

**Comment by vxsx** [comment]
it is still relevant

**Comment by vxsx** [comment]
Sorry, highly unlikely that it's going to happen for 3.0/3.1.
