### ISSUE TITLE
Bug with changing of child plugins in structure mode if this plugins is not rendered in template.

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#6044]
### Summary

Sometimes I need not render child plugins by some conditions, for example:

```
{% if can_see_plugin %}
    <h2>My plugin title: {{ instance.title }}</h2>
    {% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% endfor %}
{% else %}
    <p>You can not see plugin.</p>
{% endif %}
```

When I try change child plugins, editable form of child plugin is not opened by double click or click by "edit" icon in structure mode. Also I can not move this child plugin in other place in this placeholder (or other placeholder).

Now I have to use workaround:

```
{% if can_see_plugin %}
    <p>My plugin</p>
    {% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% endfor %}
{% else %}
    <p>You can not see plugin.</p>
    <div style="display: none;">{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% endfor %}</div>
{% endif %}
```

With this workaround I can change child plugin.

### Expected behaviour

I can change child plugin without the need of rendering of child plugins in template.

#### Actual behaviour

Editable form of child plugins can not open if I don't use `{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% endfor %}` in template.

#### Environment

* Python version: 2.7
* Django version: 1.10.7
* django CMS version: 3.4.2

**Comment by czpython** [comment]
@vxsx was this addressed by https://github.com/divio/django-cms/pull/5375?

**Comment by vxsx** [comment]
@czpython #5375 addressed the case when plugin author explicitly rendered plugin js initialization without rendering it's DOM and the cases there plugin templates were without own markup, doesn't fix this, as js still has to be rendered. I'll have to check if we fixed it on 3.5 (probably not)

**Comment by czpython** [comment]
@vivazzi 
Currently the cms does not support rendering a plugin's structure only. There's some internals you could leverage for this but I don't recommend it because a lot of these have been removed/rewritten for 3.5. We've started the decoupling of content / structure but this is an ongoing effort.

**Comment by vivazzi** [comment]
@czpython thank you for fast answer!
