### ISSUE TITLE
PageField, second dropdown still sometimes empty on 3.4.4

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#6073]
### Summary

the second dropdown (for selecting a page) is sometimes (most of the times it works!) empty. the error is this one: `Uncaught TypeError: Cannot read property '_pageSelectWidgets' of undefined`. I know this should have been resolved (been discussed: #5631, #5724, including a solution: #5637), I just dont know why this keeps coming up on my installations.

It's probably one of 10 times this occurs (or even less), and very hard to reproduce, and driving me crazy. It seems the CMS global variable is available, but not the `Widgets` attribute (not sure, though ;-). Right here: https://github.com/divio/django-cms/blob/3.4.4/cms/static/cms/js/widgets/forms.pageselectwidget.js#L83 

I am not using djangocms-text-ckeditor, if this helps. When disabling the cache in developer tools (chrome), this never occured. May be an async/$.ready/cache issue (cached bundle loaded before inline js? strange...)?

### Expected behaviour

dropdown not being empty

### Actual behaviour

dropdown empty (---)

### Environment

* Python version: 2.7.13
* Django version: 1.9.13
* django CMS version: 3.4.4

**Comment by czpython** [comment]
Hello @benzkji,
Can you try the release/3.4.x branch?
I believe we fixed another issue with this for 3.4.5

**Comment by benzkji** [comment]
thx, will do so.

**Comment by benzkji** [comment]
Problem persists. I've installed from github, resources come from /public/static/cms/js/dist/3.4.5rc1/

**Comment by benzkji** [comment]
Really dont know where to attack from...if you want can close this, as it seems not relevant to others?

**Comment by czpython** [comment]
ping @vxsx

**Comment by czpython** [comment]
@benzkji Could you provide us an environment where we can reproduce this? Maybe a dockerfile or if you're using divio cloud, a link to the site?

**Comment by benzkji** [comment]
Will try to make it reproducable.

For now: If I add a debug js to my admin, with the following:

    django.jQuery(document).ready(function($) {
        console.log(window.CMS);
    });

if things go wrong, `window.CMS` doesnt have the `PageSelectWidget` attribute. If it works, it is there. For me, this means that `window.CMS` is not the same when used inline and in the widget/bundle code. But how come so?!

Firefox seems to be the browser this occurs (Linux and Win). It's about 50/50 working and then again not.

**Comment by benzkji** [comment]
If I add `settings.STATIC_URL + 'cms/js/dist/3.4.4/bundle.admin.base.min.js',` to my admin's Media, things always work (will check back if this is the case for the client as well ;-). I remember to have used this before?!

**Comment by benzkji** [comment]
Also may be important: The field is displayed in a `StackedInline`. Sorry to mention it this late. Inline may be evil, but this time I dont think it's the reason?!

**Comment by czpython** [comment]
Ah, inlines change the game :)
Probably the issue happens when you add a new row through the "Add another" button.

**Comment by benzkji** [comment]
sorry, absorbed.

funny thing is, no. either all inlines work, or they all dont (only a "---" is selectable then).

**Comment by czpython** [comment]
@vxsx 
This was fixed in https://github.com/divio/django-cms/commit/d7ee89da24ee687ac5b3bb08f671de90fa1010dc.
Can you backport it to 3.4.x?
